runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /.*
    script: main.app
  - url: /stylesheets
    static_dir: stylesheets
  - url: /images
    static_dir: images

libraries:
  - name: webapp2
    version: latest
  - name: jinja2
    version: latest
